# cc_snapshot_guard.ps1
# Stop hook — fires automatically when Claude Code session ends.
# Ensures cc_context_snapshot.md is never stale after a session.
# If wrap-session already updated it (within 30 min), does nothing.
# If not: appends a session-end stamp so /cc bridge knows context may be stale.

$snapFile = "C:\Users\raest\Documents\Karma_SADE\cc_context_snapshot.md"
$thresholdMinutes = 30

if (Test-Path $snapFile) {
    $lastWrite = (Get-Item $snapFile).LastWriteTime
    $ageMinutes = ((Get-Date) - $lastWrite).TotalMinutes

    if ($ageMinutes -gt $thresholdMinutes) {
        $stamp = @"


## Session End Guard (auto-stamped)
Session ended: $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')
WARNING: wrap-session was not invoked this session. Snapshot content is stale.
Action required at next session: run /resurrect, then /wrap-session to refresh.
"@
        Add-Content -Path $snapFile -Value $stamp -Encoding UTF8
        Write-Host "SNAPSHOT GUARD: snapshot was $([math]::Round($ageMinutes, 1)) min stale. Stamped with session-end marker."
    } else {
        Write-Host "SNAPSHOT GUARD: snapshot is fresh ($([math]::Round($ageMinutes, 1)) min old). wrap-session ran. OK."
    }
} else {
    $stub = @"
# CC Context Snapshot
Generated: $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ') (auto-guard — file was missing)

## WARNING
This snapshot was auto-generated by the session-end guard. wrap-session was not invoked.
Content is minimal. Run /resurrect at next session start, then /wrap-session immediately.

## Identity
CC (Ascendant) — responding via P0N-A bridge (hub.arknexus.net/cc).
Inference backend: llama3.1:8b (local Ollama). Anthropic-independent.

## Hierarchy
SOVEREIGN: Colby | ASCENDANT: CC | ARCHONPRIME: Codex | ARCHON: KCC | INITIATE: Karma
"@
    Set-Content -Path $snapFile -Value $stub -Encoding UTF8
    Write-Host "SNAPSHOT GUARD: snapshot was MISSING. Created minimal stub."
}
